### ISSUE TITLE
The [Header] drop-down switch on the small screen is not flexible

### ISSUE THREAD

**Issue by webvs2** [themefisher/pinwheel-astro#8]
Only down ` id =dropdown-button `element, hopefully more flexible general

**Comment by webvs2** [comment]
![image](https://github.com/themefisher/pinwheel-astro/assets/30883395/d3a9e6bd-8034-4892-ba38-4efc0af38ced)

**Comment by tfsomrat** [comment]
Hey @webvs2, I am not getting it properly what you are trying to say. can you please explain a little bit? thanks

**Comment by webvs2** [comment]
@tfsomrat  Thank you for your attention;
This problem does not take effect when I put the page in a small resolution, and only the first one can drop down to display its option. I looked at the reason and observed that id was used as the trigger of the click event, which means that only one can take effect, but I added many navigation with 'children', and the others were invalid, so I improved it

**Comment by tfsomrat** [comment]
You can create a PR to contribute on this theme, it will be great. thanks

**Comment by webvs2** [comment]
@#9

**Comment by tfsomrat** [comment]
thanks

**Comment by webvs2** [comment]
@tfsomrat  You are welcome, it should be, and thank you very much for this template project, which makes me better to build the website. 😊
